version: '3.4'

volumes:
  tntauthenticator:
  mssqldata:
  mssqllog:
  mssqlsecrets:
  pgsqldata:
  pgsql:
  mongo:
  mongoConfigdb:
  mongodb:
  mssql:

networks:
   tnt-bridge-network:
     driver: bridge
     ipam:
        config:
            - subnet: 10.5.0.0/17
              gateway: 10.5.0.1
services:

  pgsql:
    extends:
      file: ../../TNTAuthenticator/docker-compose.yml
      service: pgsql  
  mssql:
    extends:
      file: ../../TNTAuthenticator/docker-compose.yml
      service: mssql 
  mongo:
    extends:
      file: ../../TNTAuthenticator/docker-compose.yml
      service: mongo 

  
  tntauthenticator:
    extends:
      file: ../../TNTAuthenticator/docker-compose.yml
      service: tntauthenticator 
    ports:
      - '4001:8081'
      - '8001:8080'
      
    volumes:
     - tntauthenticator:/home/app/Storage
    networks:
        tnt-bridge-network:
            ipv4_address: 10.5.0.118
  
  tntparking-backend:
    image: ${DOCKER_REGISTRY-}tntparking_backend
    build:
      context: .
      dockerfile: TNTParking-Backend/Dockerfile
    
    networks:
        tnt-bridge-network:
            ipv4_address: 10.5.0.70
    ports:
       - '4019:8081'
       - '8019:8080'
    environment:
        CORS_ALLOWED_ORIGINS: http://localhost;http://localhost:4200;https://localhost:4200;https://localhost:4001;https://localhost:4002;https://localhost:4004;https://localhost:4005;https://localhost:4006;https://auth.tntsoftware.ro;https://ngsi-ld.smartcitymanager.com;https://portal.smartcitymanager.com
