USE [master]
GO
/****** Object:  Database [TNTParking]    Script Date: 25.07.2024 10:34:15 ******/
CREATE DATABASE [TNTParking]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TNTParking', FILENAME = N'/var/opt/mssql/data/TNTParking.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TNTParking_log', FILENAME = N'/var/opt/mssql/data/TNTParking_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [TNTParking] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TNTParking].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TNTParking] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TNTParking] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TNTParking] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TNTParking] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TNTParking] SET ARITHABORT OFF 
GO
ALTER DATABASE [TNTParking] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TNTParking] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TNTParking] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TNTParking] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TNTParking] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TNTParking] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TNTParking] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TNTParking] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TNTParking] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TNTParking] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TNTParking] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TNTParking] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TNTParking] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TNTParking] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TNTParking] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TNTParking] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TNTParking] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TNTParking] SET RECOVERY FULL 
GO
ALTER DATABASE [TNTParking] SET  MULTI_USER 
GO
ALTER DATABASE [TNTParking] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TNTParking] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TNTParking] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TNTParking] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TNTParking] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'TNTParking', N'ON'
GO
ALTER DATABASE [TNTParking] SET QUERY_STORE = OFF
GO
ALTER DATABASE [TNTParking] SET  READ_WRITE 
GO
